project_name: cuelsp

builds:
  - id: darwin-amd64
    main: ./cmd/cuelsp/
    goos:
      - darwin
    goarch:
      - amd64
  - id: darwin-arm64
    main: ./cmd/cuelsp/
    goos:
      - darwin
    goarch:
      - arm64
  - id: linux-arm64
    main: ./cmd/cuelsp/
    goos:
      - linux
    goarch:
      - arm64
  - id: linux-amd64
    main: ./cmd/cuelsp/
    goos:
      - linux
    goarch:
      - amd64
  - id: windows-amd64
    main: ./cmd/cuelsp/
    goos:
      - windows
    goarch:
      - amd64

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^doc:"
      - "^test:"
      - "^tests:"
      - "^ci:"
      - "^website:"
      - "^infra:"
      - "^chore:"
      - "^build\\(deps\\):"
      - "^build\\(deps-dev\\):"
      - "^Merge pull request"
