project_name: daggerlsp

builds:
  - id: darwin-amd64
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CCX=o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
  - id: darwin-arm64
    env:
      - CGO_ENABLED=1
      - CC=oa64-clang
      - CCX=oa64-clang++
    goos:
      - darwin
    goarch:
      - arm64
  - id: linux-arm64
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CCX=aarch64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - arm64
  - id: linux-amd64
    env:
      - CGO_ENABLED=1
      - CC=gcc
      - CCX=g++
    goos:
      - linux
    goarch:
      - amd64
  - id: windows-amd64
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CCX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^doc:"
      - "^test:"
      - "^tests:"
      - "^ci:"
      - "^website:"
      - "^infra:"
      - "^chore:"
      - "^build\\(deps\\):"
      - "^build\\(deps-dev\\):"
      - "^Merge pull request"
